### ISSUE TITLE
Issue running configure.py from path other than local.

### ISSUE THREAD

**Issue by huntrontrakkr** [rticommunity/connextdds-py#34]
Hello,

As part of our CI scripting, we are attempting to build-out the library either as a distributable from a CI or in the install script itself for a software package.  The issue lies in attempting to run the install script from any other path other than directly within the directory. i.e.:

```
python ./connextdds-py/configure.py -j 4 -m -d x64Linux4gcc7.3.0
```

This results in:

```
  File "./connextdds-py/configure.py", line 381, in <module>
    main()
  File "./connextdds-py/configure.py", line 367, in main
    update_config(
  File "./connextdds-py/configure.py", line 215, in update_config
    requires = ast.literal_eval(config.get('build-system', 'requires'))
  File "/home/whunter/anaconda3/envs/dds-server-clone/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/home/whunter/anaconda3/envs/dds-server-clone/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'build-system'
```

If there is a good workaround please advise. As always, appreciated.

**Comment by marc-chiesa** [comment]
There were some relative path issues in configure.py. Please try pulling the latest from the develop branch and see if that resolves your CI issues.

**Comment by huntrontrakkr** [comment]
That definitely did, thanks! I'll revise my script once the change has been pulled into the main branch.
