### ISSUE TITLE
6.1.0 not supported

### ISSUE THREAD

**Issue by Pro** [rticommunity/connextdds-py#36]
Is support for RTI Connext DDS 6.1.0 planned?

Currently, building connextdds-py fails with:
```
 /tmp/pip-5cyse_t7-build/modules/connextdds/src/rti/core/status/DataReaderCacheStatus.cpp: In lambda function:
  /tmp/pip-5cyse_t7-build/modules/connextdds/src/rti/core/status/DataReaderCacheStatus.cpp:36:44: error: ‘const native_type {aka const struct DDS_DataReaderCacheStatus}’ has no member named ‘instance_count’; did you mean ‘sample_count’?
               return cs.native().instance_count;
                        ^~~~~~~~~~~~~~
                        sample_count
  /tmp/pip-5cyse_t7-build/modules/connextdds/src/rti/core/status/DataReaderCacheStatus.cpp: In lambda function:
  /tmp/pip-5cyse_t7-build/modules/connextdds/src/rti/core/status/DataReaderCacheStatus.cpp:42:44: error: ‘const native_type {aka const struct DDS_DataReaderCacheStatus}’ has no member named ‘instance_count_peak’; did you mean ‘sample_count_peak’?
               return cs.native().instance_count_peak;
                        ^~~~~~~~~~~~~~~~~~~
                        sample_count_peak
```

Steps to reproduce:
1. Install 6.1.0 (rti_connext_dds-6.1.0-lm-x64Linux4gcc7.3.0.run)
2. Clone https://github.com/rticommunity/connextdds-py (current master)
3. Run "python3 configure.py --tcp x64Linux4gcc7.3.0"
4. python3 -m pip install .

**Comment by marc-chiesa** [comment]
6.1.0 is not currently supported but we are planning to add support.

**Comment by Pro** [comment]
Is there any rough estimate when it will be supported?
Days, weeks, months?

**Comment by marc-chiesa** [comment]
I'd put an estimate at roughly two weeks, possibly earlier for a feature-complete development branch.

**Comment by marc-chiesa** [comment]
Initial 6.1.0 support being tested in branch [feature/connext-6.1.0](https://github.com/rticommunity/connextdds-py/tree/feature/connext-6.1.0)
